
microservice:
   payment-service:
     endpoints:
       endpoint:
         url: http://PAYMENT-SERVICE/payment/doPayment
   order-service:
    endpoints:
       endpoint:
         url: http://ORDER-SERVICE/order/bookOrder
   
