eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defalultZone: http://localhost:8761/eureka/
  instance:
    hostname: LAPTOP-7DTQQ2IL
microservice:
   payment-servie:
     endpoints:
       endpoint:
         uri= http://PAYMENT-SERVICE/payment/doPayment
   order-servie:
    endpoints:
       endpoint:
         uri= http://ORDER-SERVICE/order/bookOrder
   
