eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defalultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
microservice:
   payment-service:
     endpoints:
       endpoint:
         url: http://PAYMENT-SERVICE/payment/doPayment
   order-service:
    endpoints:
       endpoint:
         url: http://ORDER-SERVICE/order/bookOrder
   
